defaults:
  - _self_
  - dataset: ???

random_seed: 123

training:

  # Number of training instances for each relevant document.
  num_instances_per_positive: 1

  # Whether to balance the total number of instances for each query based on its number of positives.
  balance_queries: False

  # Whether to balance the total number of positives and negatives (pointwise).
  balance_labels: True
