defaults:
  - _self_
  - dataset: ???

random_seed: 123

training:

  # number of negative documents to sample for each positive
  num_negatives: 1

  # whether to balance the total number of positives and negatives (pointwise training)
  balance_labels: True

  # whether to balance the total number of instances for each query based on its number of positives
  balance_queries: False
